server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:genz;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: warn

# Allow local dev frontend
app:
  cors:
    origins: http://localhost:5173